# This YAML applies a ConfigMap that contains the main OPA policy and default response. 
# This policy is used as an entry-point for policy evaluations and returns allowed:true if policies are not matched to inbound data.

kind: ConfigMap
apiVersion: v1

metadata:
  name: policy-default
  namespace: opa
  labels:
    openpolicyagent.org/policy: rego
data:
  main: |
    package system

    import data.cloud_platform.admission

    main = {
      "apiVersion": "admission.k8s.io/v1beta1",
      "kind": "AdmissionReview",
      "response": response,
    }

    default response = {"allowed": true}

    response = {
        "allowed": false,
        "status": {
            "reason": reason,
        },
    } {
        reason = concat(", ", admission.deny)
        reason != ""
    }