---
apiVersion: v1
kind: Service
metadata:
  name: {{  template "fluentd-es.fullname" . }}
  labels:
    k8s-app: fluentd-es
    version: {{ .Values.image.tag }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
  - name: metrics
    port: 24231
    protocol: TCP
    targetPort: 24231
  selector:
    app: {{ .Release.Name }}
    version: {{ .Values.image.tag }}
  type: ClusterIP
