apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: default
  namespace: ingress-controllers
spec:
  secretName: default-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: '*.apps.cloud-platform-test-8.k8s.integration.dsd.io'
  acme:
    config:
    - dns01:
        provider: route53
      domains:
      - '*.apps.cloud-platform-test-8.k8s.integration.dsd.io'
