
name: Lint Code Base

on:
  push:
    branches-ignore:
      - 'master'
      - 'main'

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Remove files before linting
        run: | 
          ls
          find . -iname *.tfvars -exec rm -rf {} \;
          rm -rf terraform/cloud-platform-eks/cluster.tf 
      - name: Lint Code Base
        uses: docker://github/super-linter:v3.1.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: 'main'
